services:
  Pokedex.Pokemon.PokemonRepository:
    class: ../repositories/PokeApiPokemonRepository
    arguments: []

  Pokedex.Pokemon.PokemonFinder:
    class: ../../domain/PokemonFinder
    arguments: ['@Pokedex.Pokemon.PokemonRepository']

  Pokedex.Pokemon.PokemonFavoriteCounterIncrementer:
    class: ../../domain/PokemonFavoriteCounterIncrementer
    arguments: ['@Pokedex.Pokemon.PokemonRepository']

  Pokedex.Pokemon.GetPokemonById:
    class: ../../application/GetPokemonById
    arguments: ['@Pokedex.Pokemon.PokemonFinder']

  Pokedex.Pokemon.IncrementPokemonFavoriteCounterById:
    class: ../../application/IncrementPokemonFavoriteCounterById
    arguments: ['@Pokedex.Pokemon.PokemonFavoriteCounterIncrementer', '@Pokedex.Pokemon.PokemonFinder']
